// <auto-generated />
namespace RemoteHotel.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _12022019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12022019));
        
        string IMigrationMetadata.Id
        {
            get { return "201902121658441_12-02-2019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
